version: "2"
services:
  vpn:
    image: dperson/openvpn-client:latest
    container_name: vpn
    cap_add:
      - net_admin
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z
      - ${ROOT}/configs/vpn:/vpn
    security_opt:
      - label:disable
    ports:
      - 8080:8080 #sabnzbd webui port
      - 9090:9090 #sabnzbd webui port
      - 7878:7878 #radarr webui port
      - 8989:8989 #sonarr webui port
      - 6767:6767 #bazarr webui port
    command: '-r 10.0.0.0/24'

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/configs/SABnzbd:/config
      - ${ROOT}/downloads:/downloads
    restart: unless-stopped
    depends_on:
      - vpn
    
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/configs/radarr_config:/config
      - /mnt/movies:/movies
      - ${ROOT}/downloads:/downloads
    restart: unless-stopped
    depends_on:
      - vpn
      - sabnzbd

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/configs/NzbDrone:/config
      - /mnt/tv:/tv
      - ${ROOT}/downloads:/downloads
    restart: unless-stopped
    depends_on:
      - vpn
      - sabnzbd

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/configs/bazarr:/config
      - /mnt/movies:/movies
      - /mnt/tv:/tv
    restart: unless-stopped
    depends_on:
      - vpn
      - sabnzbd
      - radarr
      - sonarr